---

- when: not containers_playbook_uid and not containers_playbook_gid
  block:
    - name: Ensure containers group is created
      ansible.builtin.group:
        name: "{{ containers_playbook_user_groupname }}"
        gid: "{{ omit if containers_playbook_gid is none else containers_playbook_gid }}"
        state: present
      register: containers_base_group_result

    - name: Ensure containers user is created
      ansible.builtin.user:
        name: "{{ containers_playbook_user_username }}"
        uid: "{{ omit if containers_playbook_uid is none else containers_playbook_uid }}"
        state: present
        group: "{{ containers_playbook_user_groupname }}"
        home: "{{ containers_playbook_user_home }}"
        create_home: false
        system: true
      register: containers_base_user_result
    
    - name: Initialize containers_playbook_uid and containers_playbook_gid
      ansible.builtin.set_fact:
        containers_playbook_uid: "{{ containers_base_user_result.uid }}"
        containers_playbook_gid: "{{ containers_base_group_result.gid }}"
