- name: Update web servers
  hosts: containers
  remote_user: "{{ ansible_user }}"
  become: yes
  become_method: sudo

  collections:
    - containers.podman


  roles:
    - role: containers/playbook_base
      tags:
        - always
    - role: containers/traefik
      tags:
        - always
    - role: containers/grafana
      tags:
        - always
